### ISSUE TITLE
Benchmarking reveal added overhead in the feature/subsetting

### ISSUE THREAD

**Issue by HenrikBengtsson** [Dongcan-Jiang/matrixStats#11]
The observation that valgrind tests [times out](https://travis-ci.org/HenrikBengtsson/matrixStats/jobs/70546639) on 'feature/subsetting' ([but not](https://travis-ci.org/HenrikBengtsson/matrixStats/jobs/70552281) on 'develop') got me to run benchmarks on the 'develop' branch and the 'feature/subsetting' branch to further narrow down what could go on.  I've added `make install_branch`, `make R_branch` and `make benchmark_branch` to both branches, e.g.

``` sh
## Install pkg in current git branch to .R/<pkg version>_<branch>/
make install_branch

## Launch R with above package on top of .libPaths()
$ git symbolic-ref --short HEAD
develop
$ make R_branch
> packageDescription("matrixStats")
Package: matrixStats
Version: 0.14.2-9000
...
-- File: /cbc/henrik/repositories/GitHub/matrixStats/.R/develop/matrixStats/Meta/package.rds
>

## Run all benchmark reports on above package
$ make benchmark_branch
```

I ran `make benchmark_branch` on the 'develop' and the 'feature/subsetting' branches on the same Linux machine.  FYI, the former took ~70 mins and the latter ~140 mins.  It's mostly the new `*_subset.md.rsp` reports that adds to the extra time.   I've make all benchmark reports available at:

   http://cbc.ucsf.edu/xfer/hb/matrixStats/benchmark/

(BTW, I bumped the version of 'feature/subsetting' to 0.14.9-9000 while keeping 'develop' at 0.14.2-9000; this should make it easier to distinguish the two.)
## Issue

Looking at the non-subsetted reports, we can see that the processing time for some of the functions have increased noticeably when going from 'develop' to 'feature/subsetting', e.g.
- colMins()/rowMins() on ['develop'](http://cbc.ucsf.edu/xfer/hb/matrixStats/benchmark/0.14.2-9000_develop/reports/colRowMins.html) and ['feature/subsetting'](http://cbc.ucsf.edu/xfer/hb/matrixStats/benchmark/0.14.9-9000_feature-subsetting/reports/colRowMins.html)
- colDiffs()/rowDiff() on ['develop'](http://cbc.ucsf.edu/xfer/hb/matrixStats/benchmark/0.14.2-9000_develop/reports/colRowDiffs.html) and ['feature/subsetting'](http://cbc.ucsf.edu/xfer/hb/matrixStats/benchmark/0.14.9-9000_feature-subsetting/reports/colRowDiffs.html)
## Action

Although the matrixStats functions are still significantly faster than alternative R functions, I am hoping that there is a "simple" solution to the recent "slowdown".  Because of this, I argue that we need to:
1. Narrow down where the dominant part of this extra/added overhead comes from.
2. Try to figure out how it can be improved.  Ideally, the overhead in the new native code should be near zero for the non-subsetting case.

I consider this important enough to allow us to break the project time plan and postpone any work on the multicore milestones.  Hopefully there is a simple answer.

**Comment by HenrikBengtsson** [comment]
BTW, I should also say that the relative performance improvement in the _subsetted_ use cases are very promising, e.g. [colMins()/rowMins()](http://cbc.ucsf.edu/xfer/hb/matrixStats/benchmark/0.14.9-9000_feature-subsetting/reports/colRowMins_subset.html). :+1:

**Comment by Dongcan-Jiang** [comment]
Hi @HenrikBengtsson 

I think the increased processing time in non-subsetted cases is mostly contributed by index calculation and value fetching.

e.g.

```
colBegin = R_INDEX_OP(COL_INDEX(ccols,jj), *, nrow);
idx = R_INDEX_OP(colBegin, +, ROW_INDEX(crows,ii));
xvalue = R_INDEX_GET(x, idx, X_NA);
```
1. As we want to deal with NA index, I check NA in `R_INDEX_OP` and `R_INDEX_GET`. I think this overhead can be removed by trickier implementation of `R_INDEX_OP` and `R_INDEX_GET` according to `ROWS_TYPE`, `COLS_TYPE` and `IDXS_TYPE`. I will try it later.
2. As we want to unify different indexing types (non-subsetted and subsetted), I use `colBegin = jj * nrow; idx = colBegin + ii;` instead of `++ kk` to update the index on the fly. This would be not so "simple" to deal with, as a solution may add lots of macro judgements to the code, making it unreadable and unmaintainable.

**Comment by Dongcan-Jiang** [comment]
Hi @HenrikBengtsson 

I've tried the first optimization in #54 and found the performance result promising.
