### ISSUE TITLE
Separate *_subset.R tests for subsetting

### ISSUE THREAD

**Issue by HenrikBengtsson** [Dongcan-Jiang/matrixStats#12]
Just as for the benchmark reports, I'd like to propose that the tests on subsetted calculations are performed in separate *_subset.R test scripts, e.g. `tests/rowMads_subset.R`.

This has a few advantages:
- Lower risk for valgrind-based testing to [timeout on Travis CI](https://travis-ci.org/HenrikBengtsson/matrixStats/jobs/70546639) due to the "10-min-without-output" timeout rule they have.
- When we later add tests for parallel processing, we can analogously add those to *_parallel.R test scripts, e.g. `tests/rowMads_parallel.R`.
- This makes it possible to run, say, only *_subset.R tests or only *_parallel.R tests, which may be need on Travis CI to meet their time constraints.

**Comment by Dongcan-Jiang** [comment]
Already separated *_subset.R tests, but still not able to overcome the 50-min limit.
https://travis-ci.org/Dongcan-Jiang/matrixStats/jobs/70730355

**Comment by HenrikBengtsson** [comment]
Thanks. So, at least it seems to solve the "10-min-without-output" limit per test script.  

I looked at some of the long running test scripts to see if they could be made quicker, but it's not clear to me how, e.g. `rowAllAnys_subset.R [238s/238s]`.  I'm surprised they take so long under valgrind.

I'll look into running two separate Travis CI jobs under valgrind for;
1. `<test>.R` scripts
2. `<test>_subset.R` scripts

Let's see how far that gets us.  Recall, the 50-min limit is per job, not for the total time of all jobs.

Would you mind creating a pull request for this new split-up test scripts?

**Comment by Dongcan-Jiang** [comment]
> Would you mind creating a pull request for this new split-up test scripts?

No problem, but I'm afraid that it might take me some days to finish the PR, as I'm not quite familiar with Travis CI. And Could you tell me how to `run_check` on some of the test files instead of all of them?

**Comment by HenrikBengtsson** [comment]
I was thinking of a PR so that the split-up tests gets into the main repository "as is".

If you look at the Travis CI [`.travis.yml`](https://github.com/HenrikBengtsson/matrixStats/blob/develop/.travis.yml#L28-L32), you'll find:

```
  matrix:
    - RVERSION=3.1.3
    - RVERSION=3.2.1
    - RVERSION=devel _R_COVR_=TRUE _R_CHECK_FULL_=TRUE
    - RVERSION=devel _R_CHECK_USE_VALGRIND_=TRUE _R_CHECK_FULL_=TRUE
```

That's defines the 4 different Travis CI jobs, cf. https://travis-ci.org/Dongcan-Jiang/matrixStats/builds/70730329.  It's the last one that [triggers](https://github.com/HenrikBengtsson/matrixStats/blob/develop/.travis.yml#L45-L51) `R CMD check --use-valgrind`.

One idea I have is to use:

```
   ...
    - RVERSION=devel _R_CHECK_USE_VALGRIND_=TRUE _R_TEST_=BASE
    - RVERSION=devel _R_CHECK_USE_VALGRIND_=TRUE _R_TEST_=SUBSET
    - RVERSION=devel _R_CHECK_USE_VALGRIND_=TRUE _R_TEST_=PARALLEL
```

and add the following to the top of each `*_subset.R` test scripts, e.g.

``` r
if (Sys.getenv("_R_TEST_", "SUBSET") != "SUBSET") quit("no")
...
source("utils/validateIndicesFramework.R")
...
```

Note that if `_R_TEST_` is _not_ set, then `Sys.getenv("_R_TEST_", "SUBSET")` will indeed return `"SUBSET"` (the default) and therefore the test script will be run by default.  It is only when `_R_TEST_` is set and to a different value than `"SUBSET"` that it will be skipped.  This has the advantage of the test script being run on CRAN and in our case whenever valgrind is not used.
