### ISSUE TITLE
CLARIFICATION: `buffer0 = buffer` the same for all threads

### ISSUE THREAD

**Issue by HenrikBengtsson** [Dongcan-Jiang/matrixStats#19]
In [METHOD_NAME_ROWS_COLS()](https://github.com/Dongcan-Jiang/matrixStats/blob/5dbadecc3168d67b7f781ecfb2bea18214c00ae9/src/rowCumsums_TYPE-template.h#L121-L136):

``` c
    R_xlen_t gap = (nv + cores - 1) / cores;
    int jj = 0;
    begin = 0;
    while (begin < nv) {
      uint8_t *args = buffer + ii;
      buffer0 = buffer;
      end = MIN(begin + gap, nv);

      PUSH_ARGUMENT(buffer, ii, buffer0);
      PUSH_ARGUMENT(buffer, ii, begin);
      PUSH_ARGUMENT(buffer, ii, end);

      pthread_create(threads+(jj++), NULL, &WRAPPER_METHOD_NAME_ROWS_COLS, args);

      begin = end;
    }
```

can `buffer0 = buffer` be moved outside the while loop to make it clear that it's value is the same for all threads.  Maybe even drop it and use `PUSH_ARGUMENT(buffer, ii, buffer)`?

**Comment by Dongcan-Jiang** [comment]
Already Fixed, but `buffer0` could not be removed, because `sizeof(buffer) = memSize0 + cores * memSize1;`
