### ISSUE TITLE
Failed to run "make covr" locally

### ISSUE THREAD

**Issue by Dongcan-Jiang** [Dongcan-Jiang/matrixStats#7]
Error in covr::coveralls(coverage = coverage, quiet = TRUE, ...) : 
Failed to upload coverage data. Reply by Coveralls: Couldn't find a repository matching this job.
Calls: source ... withVisible -> eval -> eval -> covr_package -> <Anonymous>
Execution halted

**Comment by HenrikBengtsson** [comment]
I could reproduce; I've fixed it by making `.covr-utils.R` more forgiving.  Please remove that file and retry - a newer version will be downloaded and used.

**Comment by Dongcan-Jiang** [comment]
@HenrikBengtsson  Thanks.
